services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\DefaultSearch\Asset\FieldDefinitionAdapter\TextKeywordAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "input" }
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "textarea" }


    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\DefaultSearch\Asset\FieldDefinitionAdapter\KeywordAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "select" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\DefaultSearch\Asset\FieldDefinitionAdapter\RelationAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "asset" }
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "document" }
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "object" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\DefaultSearch\Asset\FieldDefinitionAdapter\DateAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "date" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\DefaultSearch\Asset\FieldDefinitionAdapter\BooleanAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.asset.search_index_field_definition", type: "checkbox" }
